<div class="panel">
	<h2>X.DAYS 2014</h2>
	<p><a href="http://greenbyte.ch/wp-content/uploads/2013/10/XDAYSLogo2014einzeiligRGB.jpg"><img class="alignleft" style="margin-left: 15px; margin-right: 15px;" alt="xdays-logo 2014" src="http://greenbyte.ch/wp-content/uploads/2013/10/XDAYSLogo2014einzeiligRGB.jpg" width="150" height="20" /></a>Greenbyte.ch ist Medienpartner der X.DAYS 2014, die vom 19. bis 20. März im Congress Centre Kursaal Interlaken stattfinden. Über 1300 Teilnehmer aus der Schweiz besuchten den Anlass im Vorjahr. Unter dem Motto «Zwischen Welten und Wolken» beleuchtet die 10. Auflage der X.DAYS die Chancen und Herausforderungen von Mobilität und Cloud Computing. Die Messe wird von Microsoft, Canon und EMC präsentiert. Sie dient auch als Schweizer Business- und Networking-Plattform. Link: <a title="X.DAYS-Website" href="http://www.xdays.ch/">xdays.ch</a></p>
</div>
<div class="panel">
	<h2>Konferenz ICT4S</h2>
	<p><a href="http://greenbyte.ch/wp-content/uploads/2013/05/ICT4S-logo-s.jpg"><img class="alignleft" style="margin-left: 15px; margin-right: 15px;" alt="ICT4S-logo-s" src="http://greenbyte.ch/wp-content/uploads/2013/05/ICT4S-logo-s.jpg" width="149" height="60" /></a>Greenbyte.ch ist Medienpartner der internationalen Konferenz «ICT for Sustainability» (ICT4S), die vom 12. bis 16. Februar 2013 in Zürich zum ersten Mal statt fand. Sie wurde von EMPA, ETH Zürich und Universität Zürich veranstaltet. Rund 360 Teilnehmer mehrheitlich aus der Wissenschaft, aber auch aus Politik und Wirtschaft aus insgesamt 49 Ländern nahmen daran teil. Die zweite internationale Konferenz ICT4S findet statt vom 24. bis 27. August 2014 in Stockholm. Link: <a title="ICT for Sustainability Conference" href="http://ict4s.org" target="_blank">ICT4S.org</a></p>
	<p>Vorschau: <a title="Erste internationale Konferenz zu Green ICT" href="http://greenbyte.ch/12145/erste-internationale-konferenz-zu-green-ict/" target="_blank">Erste internationale Konferenz zu Green ICT<br /></a>Vorschau: <a title="Workshop zu Green-ICT-Lösungen für Lebensstil" href="http://greenbyte.ch/12448/workshop-green-ict-als-lebensstil/">Workshop: Green-ICT als Lebensstil</a></p>
	<p>Bericht: <a title="Digitaler Klimaweg führt in wolkige Zukunft" href="http://greenbyte.ch/12631/ict4s2013/" target="_blank">Digitaler Klimaweg führt in wolkige Zukunft</a></p>
</div>
<div class="panel">
	<h2>Big-Data-Erfolgsgeschichten</h2>
	<p><a href="http://greenbyte.ch/wp-content/uploads/2013/05/Big_Data_Illustration.jpg"><img class="alignleft" style="margin-left: 15px; margin-right: 15px;" alt="Big_Data_Illustration" src="http://greenbyte.ch/wp-content/uploads/2013/05/Big_Data_Illustration.jpg" width="150" height="90" /></a></p>
	<p dir="ltr">Am 14. Juni 2012 bot der erste Event der Reihe «Big Data Erfolgsgeschichten» Referenten und Projekte aus der Praxis im Hotel Radisson Blu am Zürcher Flughafen. Organisiert wurde der Premiere-Anlass für eingeladene CIO und IT-Entscheider von der Zürcher Beratungsfirma Extendance. Link: <a title="Extendance GmbH" href="http://extendance.com/" target="_blank">Extendance.com</a></p>
	<p>Gastbeitrag &amp; Vorschau: <a title="Big Data sagt Zukunft voraus" href="http://greenbyte.ch/9941/big-data-sagt-zukunft-voraus" target="_blank">Big Data sagt Zukunft voraus<br /></a>Artikel: <a title="Big Data öffnet Einsicht in Datenberg" href="http://greenbyte.ch/11742/big-data-in-der-praxis/">Big Data öffnet Einsicht in Datenberg</a></p>
	<p><span style="line-height: 1.5em;">Am 5. Juni 2013 bot der Event «3. Big Data Erfolgsgeschichten» erneut Referenten und Projekte aus der Praxis im Hotel Radisson Blu am Zürcher Flughafen. Auch dieser Anlass wurde für die eingeladenen CIO und IT-Entscheider von der Zürcher Beratungsfirma Extendance organisiert. Link: </span><a style="line-height: 1.5em;" title="Extendance GmbH" href="http://extendance.com/" target="_blank">Extendance.com</a></p>
	<p>Artikel: <a title="Big Data reift in kleinen Schritten" href="http://greenbyte.ch/13353/big-data-reift-in-kleinen-schritten/">Big Data reift in kleinen Schritten</a></p>
	<p dir="ltr"> </p>
</div>
<div class="panel">
	<h2>Data Center Management Event</h2>
	<p><a href="http://greenbyte.ch/wp-content/uploads/2013/05/microsoft-datacenter-1.jpg"><img class="alignleft" style="margin-left: 15px; margin-right: 15px;" alt="microsoft  datacenter 1" src="http://greenbyte.ch/wp-content/uploads/2013/05/microsoft-datacenter-1.jpg" width="150" /></a>Der «3. Data Center Management Event» der Zürcher Beratungsfirma Extendance fand am 5. März 2013 im UBS-Konferenzzentrum Grünenhof statt, für eingeladene CIO und IT-Entscheider. Link: <a title="Extendance GmbH" href="http://extendance.com/" target="_blank">Extendance.com</a></p>
	<p>Artikel: <a title="Disaster Recovery muss ohne Menschen auskommen" href="http://greenbyte.ch/12758/disaster-recovery-muss-ohne-menschen-auskommen/" target="_blank">Disaster Recovery muss ohne Menschen auskommen<br /></a>Artikel: <a title="Praktische Tipps zum grünen Rechenzentrum" href="http://greenbyte.ch/13245/praktische-tipps-zum-grunen-rechenzentrum/" target="_blank">Praktische Tipps zum grünen Rechenzentrum</a></p>
	<p>Der «4. Data Center Management Event» der Zürcher Beratungsfirma Extendance fand im September 2013 in der Neuen Börse Zürich statt, erneut mit eingeladenen CIO- und IT-Entscheidern von Schweizer Unternehmen. Link: <a title="Extendance GmbH" href="http://extendance.com/" target="_blank">Extendance.com</a></p>
	<p>Artikel: <a title="Regenwasser kühlt Swisscom-Cloud" href="http://greenbyte.ch/14281/regenwasser-kuehlt-swisscom-cloud/">Regenwasser kühlt Swisscom-Cloud</a></p>
	<p><a title="Disaster Recovery muss ohne Menschen auskommen" href="http://greenbyte.ch/12758/disaster-recovery-muss-ohne-menschen-auskommen/" target="_blank"> </a></p>
</div>
